apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backpack-ingress
  namespace: backpack
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`backpack.local`)
      kind: Rule
      services:
        - name: backpack-api
          port: 8080
  tls:
    certResolver: letsencrypt
    domains:
      - main: backpack.local
