apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: backpack
spec:
  template:
    spec:
      nodeSelector:
        gpu: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
