apiVersion: apps/v1
kind: Deployment
metadata:
  name: backpack-api
  labels:
    app: backpack-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backpack-api
  template:
    metadata:
      labels:
        app: backpack-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
